services:
  catalogdb:
    image: postgres:latest
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@$$w0rd
      POSTGRES_DB: CatalogDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

volumes:
  postgres_catalog:
